dist: xenial
language: python

addons:
  apt:
    packages:
    - socat

env:
  global:
  - REDIS_TAGS="2.6.17 2.8.22 3.0.7 3.2.8 4.0.11 5.0.1" INSTALL_DIR=$HOME/redis

python:
- "3.5"
- "3.6"
- "3.7"
- "nightly"
- "pypy3.5-6.0"

stages:
- lint
- test

jobs:
  include:
  - stage: lint
    name: documentation spell check
    python: "3.6"
    addons:
      apt:
        packages:
        - enchant
        - aspell
        - aspell-en
    install:
    - pip install -r docs/requirements.txt
    - pip install -e. -c tests/requirements.txt
    script: make spelling
  - &FLAKE
    name: flake
    python: "3.6"
    install:
    - pip install -r tests/requirements.txt
    script:
    - make flake
  - <<: *FLAKE
    python: "3.7"
  - &UVLOOP
    stage: test
    env: UVLOOP="y"
    python: "3.6"
  - <<: *UVLOOP
    python: "3.7"

install:
- make -j ci-build-redis
- |
    if [ "$UVLOOP" = "y" ]; then
      export TEST_ARGS="$TEST_ARGS --uvloop"
      pip install uvloop
    fi;
- pip install codecov
- pip install -r tests/requirements.txt
- pip install -e .

script:
# - make flake
- make ci-test
- make examples

cache: pip

after_script:
- codecov
